<?php require('template/header.phtml') ?>
<h3>How this MVC template works</h3>
<p>The MVC has three parts to it:</p>
<ul>
    <li>Model</li>
    <p>The model is where all the logic can be found, is the backend of the website</p>
    <li>View</li>
    <p>The view is the front-end, how the website looks</p>
    <li>Controller</li>
    <p>The controller is the middleman it controls what to show and where to send the information given. It gets the information from the view sends it to the controller gets a result and updates the view to display the result</p>
</ul>
<img src="/workshop4/MVCtemplate/images/Untitled.png" style="width: 200px">
<?php require('template/footer.phtml') ?>
